import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'data', 'templates.json');
const T = JSON.parse(readFileSync(OUT, 'utf-8'));

// === EDUCATION (教育培训) - 10 templates ===
T.push({id:"education-course-intro",title:"培训课程介绍",slug:"education-course-intro",industry:"education",task:"product-description",description:"为培训机构课程撰写介绍文案",scenario:"招生季、上线新课程时使用",notFor:"不适合用于学历教育招生",materialsNeeded:["课程名称","适合年龄","课程内容","师资介绍","课时安排"],prompt:"你是一位教育培训文案助手。请为以下课程撰写介绍。\n\n课程名称：{课程名称}\n适合年龄：{适合年龄}\n课程内容：{课程内容}\n师资：{师资介绍}\n课时：{课时安排}\n\n要求：\n1. 字数100-150字\n2. 突出课程特色和师资\n3. 不承诺考试成绩或升学结果\n4. 语气专业可信\n5. 适合公众号或传单",fieldExplanations:{"课程名称":"课程的正式名称","适合年龄":"目标学员年龄段","课程内容":"主要学什么","师资介绍":"老师的背景","课时安排":"多少课时、怎么上"},outputFormat:"100-150字课程介绍",exampleOutput:"【少儿编程启蒙班】适合6-9岁零基础小朋友。通过Scratch图形化编程，让孩子在游戏中学习逻辑思维。课程内容：基础指令→动画制作→简单游戏开发，循序渐进。授课老师计算机专业毕业，3年少儿编程教学经验。每周一次课，每次90分钟，小班制（6-8人）。免费试听一次，满意再报名（仅供格式参考）",reviewChecklist:["无成绩承诺","师资描述是否真实","课时信息准确","价格是否需要标注"],relatedTemplates:["education-enrollment","education-trial-invite"]});
T.push({id:"education-enrollment",title:"培训招生文案",slug:"education-enrollment",industry:"education",task:"campaign-copy",description:"为培训机构招生季撰写推广文案",scenario:"春季/秋季招生、暑假班招生时使用",notFor:"不适合用于学历招生广告",materialsNeeded:["招生课程","优惠政策","报名时间","联系方式"],prompt:"你是一位培训机构招生文案助手。请撰写招生推广文案。\n\n招生课程：{招生课程}\n优惠政策：{优惠政策}\n报名时间：{报名时间}\n联系方式：{联系方式}\n\n要求：\n1. 字数80-120字\n2. 突出课程价值\n3. 不承诺成绩提升\n4. 不贬低其他机构\n5. 适合朋友圈和家长群",fieldExplanations:{"招生课程":"招什么课程的学生","优惠政策":"早鸟价、团报优惠等","报名时间":"截止日期","联系方式":"电话或微信"},outputFormat:"80-120字招生文案",exampleOutput:"秋季班开始报名啦！少儿美术、书法、编程三门课程同步招生。9月1日前报名享早鸟价：单科立减200，报两科再减100。小班教学，每班限8人，报满即止。免费试听课随时预约，让孩子先体验再决定。咨询电话/微信：XXX（仅供格式参考）",reviewChecklist:["无成绩承诺","优惠信息准确","报名时间正确","联系方式有效"],relatedTemplates:["education-course-intro","education-trial-invite"]});
T.push({id:"education-trial-invite",title:"培训试听课邀约",slug:"education-trial-invite",industry:"education",task:"appointment",description:"为培训机构生成试听课邀约话术",scenario:"邀请潜在学员家长来试听时使用",notFor:"不适合用于强制推销",materialsNeeded:["课程名称","试听时间","试听内容","地址"],prompt:"你是一位培训机构课程顾问。请生成试听课邀约话术。\n\n课程：{课程名称}\n时间：{试听时间}\n内容：{试听内容}\n地址：{地址}\n\n要求：\n1. 语气友好不强迫\n2. 说明试听是免费的\n3. 降低决策门槛\n4. 字数60-100字",fieldExplanations:{"课程名称":"邀请试听什么课","试听时间":"具体时间","试听内容":"试听课会做什么","地址":"上课地点"},outputFormat:"60-100字邀约话术",exampleOutput:"XX妈妈您好～我们这周六下午2点有一节少儿编程体验课，小朋友可以动手做一个小游戏，挺有趣的。完全免费，不满意也没关系，就当让孩子体验一下。地址在XX商场3楼，方便的话带孩子来玩玩？（仅供格式参考）",reviewChecklist:["是否说明免费","语气是否自然","无强迫感","信息是否完整"],relatedTemplates:["education-enrollment","education-parent-comm"]});
T.push({id:"education-parent-comm",title:"培训家长沟通话术",slug:"education-parent-comm",industry:"education",task:"customer-service",description:"为培训机构生成与家长沟通的话术",scenario:"反馈学习情况、处理家长疑问时使用",notFor:"不适合用于投诉纠纷处理",materialsNeeded:["学员姓名","沟通主题","学习情况","建议"],prompt:"你是一位培训机构老师。请生成与家长的沟通话术。\n\n学员：{学员姓名}\n主题：{沟通主题}\n情况：{学习情况}\n建议：{建议}\n\n要求：\n1. 语气专业温和\n2. 先说优点再说不足\n3. 给出具体建议\n4. 不贬低孩子\n5. 字数80-120字",fieldExplanations:{"学员姓名":"孩子的名字","沟通主题":"要沟通什么","学习情况":"最近的学习表现","建议":"给家长的建议"},outputFormat:"80-120字家长沟通话术",exampleOutput:"XX妈妈您好，跟您反馈一下小明最近的学习情况。这个月他在课堂上的专注度有明显进步，作品完成度也越来越高，能看出来在家有练习。有一点小建议：他在色彩搭配上还可以多尝试，建议平时可以带他多看看绘本或者逛逛美术馆，培养色彩感觉（仅供格式参考）",reviewChecklist:["是否先说优点","建议是否具体","语气是否温和","无贬低孩子"],relatedTemplates:["education-course-intro","education-review-response"]});
T.push({id:"education-review-response",title:"培训机构评价回复",slug:"education-review-response",industry:"education",task:"review-response",description:"为培训机构线上评价生成回复",scenario:"收到大众点评、美团等平台评价时使用",notFor:"不适合用于纠纷处理",materialsNeeded:["评价内容","评价星级","课程名称","回复重点"],prompt:"你是一位培训机构运营。请针对评价生成回复。\n\n评价：{评价内容}\n星级：{评价星级}\n课程：{课程名称}\n重点：{回复重点}\n\n要求：\n1. 感谢反馈\n2. 针对具体内容回应\n3. 不承诺成绩\n4. 字数50-80字",fieldExplanations:{"评价内容":"家长写的评价","评价星级":"几星","课程名称":"上的什么课","回复重点":"想强调什么"},outputFormat:"50-80字评价回复",exampleOutput:"感谢您的认可！很高兴小朋友在我们这里学得开心。我们一直坚持小班教学，就是为了让每个孩子都能得到足够的关注。期待看到孩子更多的进步，有任何问题随时和我们沟通（仅供格式参考）",reviewChecklist:["无成绩承诺","语气是否专业","回复是否针对具体内容","无贬低同行"],relatedTemplates:["education-parent-comm","education-social-media"]});
T.push({id:"education-social-media",title:"培训机构朋友圈内容",slug:"education-social-media",industry:"education",task:"social-media",description:"为培训机构生成朋友圈日常内容",scenario:"展示教学日常、分享教育理念时使用",notFor:"不适合用于虚假宣传",materialsNeeded:["今日内容","教学亮点","教育小知识"],prompt:"你是一位培训机构朋友圈运营助手。请生成日常内容。\n\n内容：{今日内容}\n亮点：{教学亮点}\n知识：{教育小知识}\n\n要求：\n1. 字数50-80字\n2. 展示教学氛围\n3. 不晒成绩单\n4. 不承诺效果\n5. 适合配课堂照片",fieldExplanations:{"今日内容":"今天想分享什么","教学亮点":"课堂上的精彩瞬间","教育小知识":"可以分享的教育理念"},outputFormat:"50-80字朋友圈文案",exampleOutput:"今天编程课上，一个二年级的小朋友自己设计了一个「接苹果」的小游戏，还给游戏加了音效和计分功能。看到孩子们从「老师我不会」到「老师你看我做的」，这种变化真的很有成就感（仅供格式参考）",reviewChecklist:["无成绩展示","内容是否真实","语气是否自然","无过度宣传"],relatedTemplates:["education-short-video","education-enrollment"]});
T.push({id:"education-short-video",title:"培训机构短视频脚本",slug:"education-short-video",industry:"education",task:"short-video",description:"为培训机构短视频撰写脚本",scenario:"拍摄教学花絮、知识分享类视频时使用",notFor:"不适合用于虚假案例展示",materialsNeeded:["视频主题","拍摄内容","目标受众","时长"],prompt:"你是一位教育短视频策划。请撰写脚本。\n\n主题：{视频主题}\n内容：{拍摄内容}\n受众：{目标受众}\n时长：{时长}\n\n要求：\n1. 有教育价值\n2. 不承诺效果\n3. 适合家长观看\n4. 分镜头描述\n5. 轻松有趣",fieldExplanations:{"视频主题":"如「课堂花絮」「学习方法分享」","拍摄内容":"具体拍什么","目标受众":"给谁看","时长":"视频时长"},outputFormat:"分镜头脚本",exampleOutput:"【开场3秒】画面：孩子们围坐在桌前，专注画画。字幕「你家孩子坐不住？可能是方法不对」\n【中间20秒】画面：老师用游戏化方式引导孩子。口播「我们不会让孩子枯燥地练习，而是把每个知识点变成一个小挑战...」\n【结尾5秒】画面：孩子展示作品的笑脸。字幕「免费试听课预约中」（仅供格式参考）",reviewChecklist:["无成绩承诺","内容是否专业","拍摄方案可执行","无虚假展示"],relatedTemplates:["education-social-media","education-enrollment"]});
T.push({id:"education-seasonal",title:"培训机构季节性招生",slug:"education-seasonal",industry:"education",task:"seasonal-promo",description:"为培训机构节假日或寒暑假招生撰写文案",scenario:"暑假班、寒假班、春季班招生时使用",notFor:"不适合用于学历教育招生",materialsNeeded:["假期/季节","课程安排","优惠政策","报名截止"],prompt:"你是一位培训机构招生助手。请撰写季节性招生文案。\n\n时段：{假期或季节}\n课程：{课程安排}\n优惠：{优惠政策}\n截止：{报名截止}\n\n要求：\n1. 字数80-120字\n2. 突出假期利用价值\n3. 不制造焦虑\n4. 不承诺成绩\n5. 适合家长群发布",fieldExplanations:{"假期或季节":"如「暑假」「寒假」","课程安排":"开什么课、怎么安排","优惠政策":"有什么优惠","报名截止":"什么时候截止"},outputFormat:"80-120字招生文案",exampleOutput:"暑假班开始报名！7-8月开设：少儿美术、书法、编程三门课程，每周3次课，让孩子假期有事做、有收获。早鸟优惠：6月30日前报名立减300，两科连报再减200。小班制，每班限8人。不想让孩子整个暑假都在家看平板的家长，可以了解一下（仅供格式参考）",reviewChecklist:["无焦虑营销","优惠信息准确","截止日期正确","无成绩承诺"],relatedTemplates:["education-enrollment","education-trial-invite"]});
T.push({id:"education-complaint",title:"培训机构投诉处理",slug:"education-complaint",industry:"education",task:"complaint-handling",description:"为培训机构处理家长投诉生成话术",scenario:"家长投诉教学质量、退费等问题时使用",notFor:"不适合用于法律纠纷",materialsNeeded:["投诉内容","核实情况","解决方案","后续安排"],prompt:"你是一位培训机构校长。请针对家长投诉生成处理话术。\n\n投诉：{投诉内容}\n情况：{核实情况}\n方案：{解决方案}\n后续：{后续安排}\n\n要求：\n1. 重视家长反馈\n2. 不推卸责任\n3. 给出具体方案\n4. 语气诚恳\n5. 字数100-150字",fieldExplanations:{"投诉内容":"家长投诉什么","核实情况":"了解到的实际情况","解决方案":"如何解决","后续安排":"后续如何改进"},outputFormat:"100-150字投诉处理话术",exampleOutput:"XX妈妈您好，非常感谢您的反馈，也很抱歉让您有了不好的体验。关于您提到的老师上课迟到问题，我已经核实确认，确实是该老师时间管理出了问题。处理方案：1.本周补上缺失的课时；2.该老师已做严肃谈话；3.后续我会不定期巡课。如果您对目前的老师不满意，也可以免费转到另一位老师的班级。再次向您道歉（仅供格式参考）",reviewChecklist:["是否承认问题","方案是否具体","语气是否诚恳","后续改进是否可行"],relatedTemplates:["education-parent-comm","education-review-response"]});
T.push({id:"education-brand-story",title:"培训机构品牌故事",slug:"education-brand-story",industry:"education",task:"brand-story",description:"为培训机构撰写品牌介绍",scenario:"更新官网、制作宣传册时使用",notFor:"不适合用于资质申报",materialsNeeded:["创办初衷","教学理念","师资特色","办学成果"],prompt:"你是一位教育品牌文案助手。请撰写品牌故事。\n\n初衷：{创办初衷}\n理念：{教学理念}\n师资：{师资特色}\n成果：{办学成果}\n\n要求：\n1. 字数150-250字\n2. 体现教育情怀\n3. 不夸大成果\n4. 不承诺升学\n5. 真实可信",fieldExplanations:{"创办初衷":"为什么办这个机构","教学理念":"怎么看待教育","师资特色":"老师有什么特别的","办学成果":"做了多久、服务了多少学生"},outputFormat:"150-250字品牌故事",exampleOutput:"2019年创办这个画室，是因为我自己小时候学画画的经历——老师只让临摹，从不问我想画什么。所以我想做一个「让孩子自由表达」的地方。我们不追求画得像，而是鼓励孩子用画笔讲自己的故事。五年了，从最初5个学生到现在稳定在60多人，很多孩子从幼儿园一直跟到小学毕业。我们的老师都是美院毕业，但更重要的是，他们真的喜欢和孩子相处（仅供格式参考）",reviewChecklist:["故事是否真实","无升学承诺","理念是否清晰","成果描述是否客观"],relatedTemplates:["education-social-media"]});

// === PHOTOGRAPHY (摄影工作室) - 10 templates ===
// MARKER_PHOTOGRAPHY

writeFileSync(OUT, JSON.stringify(T, null, 2), 'utf-8');
console.log(`Part 2: Total ${T.length} templates`);
