import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'data', 'templates.json');
const T = JSON.parse(readFileSync(OUT, 'utf-8'));

// === FITNESS (健身瑜伽) - 10 templates ===
T.push({id:"fitness-course-intro",title:"健身课程介绍",slug:"fitness-course-intro",industry:"fitness",task:"product-description",description:"为健身房/瑜伽馆课程撰写介绍文案",scenario:"上线新课程、更新课表时使用",notFor:"不适合用于医疗康复方案",materialsNeeded:["课程名称","适合人群","课程内容","时长频次","教练介绍"],prompt:"你是一位健身行业文案助手。请为以下课程撰写介绍。\n\n课程：{课程名称}\n适合：{适合人群}\n内容：{课程内容}\n时长：{时长频次}\n教练：{教练介绍}\n\n要求：\n1. 字数100-150字\n2. 突出课程特色\n3. 不承诺减重/塑形效果\n4. 语气积极专业\n5. 适合公众号或海报",fieldExplanations:{"课程名称":"如「燃脂搏击」「阴瑜伽」","适合人群":"什么基础的人适合","课程内容":"主要练什么","时长频次":"一节多久、建议频次","教练介绍":"教练的资质"},outputFormat:"100-150字课程介绍",exampleOutput:"【燃脂搏击课】适合想提升心肺、释放压力的你。课程融合拳击、踢腿等动作，配合音乐节奏，全程45分钟，运动量适中。零基础友好，教练会分解每个动作。建议每周2-3次，坚持一段时间体能会有明显变化。教练小王：ACE认证私教，5年团课经验。每周二四六晚7:30，小班制12人（仅供格式参考）",reviewChecklist:["无减重承诺","教练资质是否真实","时间信息准确","适合人群描述合理"],relatedTemplates:["fitness-campaign","fitness-membership"]});
T.push({id:"fitness-campaign",title:"健身活动促销文案",slug:"fitness-campaign",industry:"fitness",task:"campaign-copy",description:"为健身房促销活动撰写文案",scenario:"开业促销、节日活动、体验课推广时使用",notFor:"不适合用于虚假宣传",materialsNeeded:["活动主题","优惠内容","活动时间","报名方式"],prompt:"你是一位健身房营销助手。请撰写活动文案。\n\n主题：{活动主题}\n优惠：{优惠内容}\n时间：{活动时间}\n报名：{报名方式}\n\n要求：\n1. 字数80-120字\n2. 激发运动热情\n3. 不承诺效果\n4. 不制造身材焦虑\n5. 适合朋友圈",fieldExplanations:{"活动主题":"如「新年焕新计划」「夏日体验周」","优惠内容":"具体优惠","活动时间":"起止日期","报名方式":"怎么报名"},outputFormat:"80-120字活动文案",exampleOutput:"新年想给自己一个改变的开始？1月办卡享开年价：年卡立减500，季卡送一个月。新会员还赠送体测一次+私教体验课一节，帮你了解自己的身体状况。不管是想增强体质还是释放压力，运动都是个好选择。活动截止1.31，前台或微信报名都行（仅供格式参考）",reviewChecklist:["无效果承诺","无身材焦虑","优惠信息准确","时间是否正确"],relatedTemplates:["fitness-course-intro","fitness-trial"]});
T.push({id:"fitness-trial",title:"健身体验课邀约",slug:"fitness-trial",industry:"fitness",task:"appointment",description:"为健身房生成体验课邀约话术",scenario:"邀请潜在客户来体验时使用",notFor:"不适合用于强制推销",materialsNeeded:["体验课程","时间安排","地址","注意事项"],prompt:"你是一位健身房课程顾问。请生成体验课邀约话术。\n\n课程：{体验课程}\n时间：{时间安排}\n地址：{地址}\n注意：{注意事项}\n\n要求：\n1. 语气友好不强迫\n2. 降低门槛\n3. 说明免费\n4. 字数60-100字",fieldExplanations:{"体验课程":"可以体验什么课","时间安排":"什么时候可以来","地址":"健身房地址","注意事项":"需要带什么"},outputFormat:"60-100字邀约话术",exampleOutput:"最近有没有想运动的想法？我们这周有免费体验课：瑜伽、搏击、单车都可以选。不用有基础，穿运动服来就行，我们提供毛巾和水。地址在XX商场B1层，停车方便。来感受一下，不喜欢也没关系，就当活动活动（仅供格式参考）",reviewChecklist:["是否说明免费","语气是否自然","无强迫感","信息是否完整"],relatedTemplates:["fitness-campaign","fitness-membership"]});
T.push({id:"fitness-membership",title:"健身会员续费话术",slug:"fitness-membership",industry:"fitness",task:"membership",description:"为健身房会员续费或升级撰写话术",scenario:"会员即将到期、推出续费优惠时使用",notFor:"不适合用于强制续费",materialsNeeded:["会员称呼","当前卡种","续费优惠","到期时间"],prompt:"你是一位健身房会员顾问。请生成续费话术。\n\n会员：{会员称呼}\n卡种：{当前卡种}\n优惠：{续费优惠}\n到期：{到期时间}\n\n要求：\n1. 语气友好不施压\n2. 突出续费优惠\n3. 不强制\n4. 字数60-100字",fieldExplanations:{"会员称呼":"会员怎么称呼","当前卡种":"现在是什么卡","续费优惠":"续费有什么优惠","到期时间":"什么时候到期"},outputFormat:"60-100字续费话术",exampleOutput:"张哥，你的年卡下个月15号到期，提前跟你说一声。这个月续费的话有个老会员优惠：续一年送两个月，相当于14个月的使用时间。你最近来得挺勤的，坚持下去状态会越来越好。要不要续上？不着急决定，有问题随时问我（仅供格式参考）",reviewChecklist:["到期时间是否正确","优惠是否真实","语气是否友好","无强制感"],relatedTemplates:["fitness-campaign","fitness-social-media"]});
T.push({id:"fitness-social-media",title:"健身房朋友圈内容",slug:"fitness-social-media",industry:"fitness",task:"social-media",description:"为健身房生成朋友圈日常内容",scenario:"日常发圈展示训练氛围、分享健身知识时使用",notFor:"不适合用于医疗建议",materialsNeeded:["今日内容","健身知识","训练氛围"],prompt:"你是一位健身房朋友圈运营助手。请生成日常内容。\n\n内容：{今日内容}\n知识：{健身知识}\n氛围：{训练氛围}\n\n要求：\n1. 字数50-80字\n2. 传递积极能量\n3. 不制造焦虑\n4. 不承诺效果\n5. 适合配训练照片",fieldExplanations:{"今日内容":"今天想分享什么","健身知识":"实用的健身小贴士","训练氛围":"今天的训练氛围"},outputFormat:"50-80字朋友圈文案",exampleOutput:"今天晚课搏击班满员了，大家跟着音乐打得特别带劲。有个会员说「上了一天班，打完这45分钟感觉压力全释放了」。运动的好处不只是身体上的，心情也会变好。明天还有名额，想来的提前约（仅供格式参考）",reviewChecklist:["无身材焦虑","无效果承诺","语气是否积极","内容是否真实"],relatedTemplates:["fitness-short-video","fitness-course-intro"]});
T.push({id:"fitness-short-video",title:"健身短视频脚本",slug:"fitness-short-video",industry:"fitness",task:"short-video",description:"为健身房短视频撰写脚本",scenario:"拍摄训练教程、课程花絮时使用",notFor:"不适合用于医疗康复指导",materialsNeeded:["视频主题","动作内容","目标受众","时长"],prompt:"你是一位健身短视频策划。请撰写脚本。\n\n主题：{视频主题}\n动作：{动作内容}\n受众：{目标受众}\n时长：{时长}\n\n要求：\n1. 动作示范清晰\n2. 强调安全\n3. 不承诺效果\n4. 适合竖屏\n5. 分镜头描述",fieldExplanations:{"视频主题":"如「办公室拉伸」「新手入门」","动作内容":"展示什么动作","目标受众":"给谁看","时长":"视频时长"},outputFormat:"分镜头脚本",exampleOutput:"【开场3秒】画面：教练站在器械区。字幕「久坐族必看！3个动作缓解腰背酸痛」\n【中间25秒】画面：依次示范猫牛式、婴儿式、鸟狗式。每个动作正面+侧面。口播要点和呼吸节奏\n【结尾5秒】字幕「每天5分钟，坚持比强度更重要」。配健身房环境镜头（仅供格式参考）",reviewChecklist:["动作是否安全","无效果承诺","示范是否清晰","无医疗建议"],relatedTemplates:["fitness-social-media","fitness-course-intro"]});
T.push({id:"fitness-review-response",title:"健身房评价回复",slug:"fitness-review-response",industry:"fitness",task:"review-response",description:"为健身房线上评价生成回复",scenario:"收到大众点评等平台评价时使用",notFor:"不适合用于纠纷处理",materialsNeeded:["评价内容","评价星级","会员情况","回复重点"],prompt:"你是一位健身房运营。请针对评价生成回复。\n\n评价：{评价内容}\n星级：{评价星级}\n会员：{会员情况}\n重点：{回复重点}\n\n要求：\n1. 感谢反馈\n2. 针对具体内容\n3. 不承诺效果\n4. 字数50-80字",fieldExplanations:{"评价内容":"客户写的评价","评价星级":"几星","会员情况":"新会员还是老会员","回复重点":"想强调什么"},outputFormat:"50-80字评价回复",exampleOutput:"感谢认可！很高兴你喜欢我们的团课氛围，搏击课确实是释放压力的好方式。坚持运动一段时间，你会感受到体能的变化。有任何课程问题随时问前台或你的顾问，我们随时在（仅供格式参考）",reviewChecklist:["无效果承诺","语气是否积极","回复是否具体","无身材评价"],relatedTemplates:["fitness-social-media","fitness-membership"]});
T.push({id:"fitness-complaint",title:"健身房投诉处理",slug:"fitness-complaint",industry:"fitness",task:"complaint-handling",description:"为健身房客户投诉生成处理话术",scenario:"会员投诉设备、环境、教练等问题时使用",notFor:"不适合用于安全事故处理",materialsNeeded:["投诉内容","核实情况","解决方案","改进措施"],prompt:"你是一位健身房店长。请针对投诉生成处理话术。\n\n投诉：{投诉内容}\n情况：{核实情况}\n方案：{解决方案}\n改进：{改进措施}\n\n要求：\n1. 诚恳道歉\n2. 给出方案\n3. 说明改进\n4. 字数80-120字",fieldExplanations:{"投诉内容":"会员投诉什么","核实情况":"实际情况","解决方案":"如何解决","改进措施":"如何改进"},outputFormat:"80-120字投诉处理话术",exampleOutput:"张哥您好，很抱歉给您带来不好的体验。关于您反映的更衣室卫生问题，我今天去检查了确实存在清洁不到位的情况。已经做了以下调整：1.增加保洁频次，从每天2次改为4次；2.每个时段有专人巡查；3.增设意见箱方便及时反馈。感谢您的监督，后续有任何问题直接找我（仅供格式参考）",reviewChecklist:["是否承认问题","方案是否具体","改进是否可行","语气是否诚恳"],relatedTemplates:["fitness-review-response"]});
T.push({id:"fitness-seasonal",title:"健身季节性活动",slug:"fitness-seasonal",industry:"fitness",task:"seasonal-promo",description:"为健身房季节性活动撰写文案",scenario:"新年健身计划、夏日减脂、秋冬养生等活动时使用",notFor:"不适合用于医疗减重方案",materialsNeeded:["季节主题","活动内容","优惠信息","活动时间"],prompt:"你是一位健身房营销助手。请撰写季节性活动文案。\n\n主题：{季节主题}\n内容：{活动内容}\n优惠：{优惠信息}\n时间：{活动时间}\n\n要求：\n1. 字数80-120字\n2. 结合季节\n3. 不制造焦虑\n4. 不承诺效果\n5. 积极正面",fieldExplanations:{"季节主题":"如「新年焕新」「夏日活力」","活动内容":"具体活动","优惠信息":"有什么优惠","活动时间":"起止日期"},outputFormat:"80-120字季节活动文案",exampleOutput:"春天来了，是时候动起来了！3月「春日焕新」活动：新会员办季卡送一个月，老会员续费享8折。另外本月新增户外跑团活动，每周六早上8点公园集合，免费参加，不限会员。春天适合开始一个新习惯，运动就是个好选择（仅供格式参考）",reviewChecklist:["无身材焦虑","无效果承诺","优惠信息准确","时间是否正确"],relatedTemplates:["fitness-campaign","fitness-membership"]});
T.push({id:"fitness-brand-story",title:"健身房品牌故事",slug:"fitness-brand-story",industry:"fitness",task:"brand-story",description:"为健身房撰写品牌介绍",scenario:"更新官网、社交媒体简介时使用",notFor:"不适合用于融资材料",materialsNeeded:["创业故事","经营理念","设施特色","团队介绍"],prompt:"你是一位品牌文案助手。请为健身房撰写品牌故事。\n\n故事：{创业故事}\n理念：{经营理念}\n设施：{设施特色}\n团队：{团队介绍}\n\n要求：\n1. 字数150-250字\n2. 传递运动态度\n3. 不制造焦虑\n4. 真实可信",fieldExplanations:{"创业故事":"为什么开健身房","经营理念":"怎么看待健身","设施特色":"设备和环境","团队介绍":"教练团队"},outputFormat:"150-250字品牌故事",exampleOutput:"开这家健身房之前，我在连锁健身房当了4年教练。离开的原因是：不想再为了卖课而卖课。2022年自己开了这家社区店，面积不大但设备齐全，最重要的是——我们不强制推销。来这里的人，有早起跑步的上班族，有带孩子来的全职妈妈，也有退休后想活动筋骨的叔叔阿姨。我们的教练都有国职证书，但更重要的是他们真的热爱运动，愿意陪你一起坚持。健身不是为了变成谁，是为了让自己状态更好（仅供格式参考）",reviewChecklist:["故事是否真实","无身材焦虑","理念是否清晰","无虚构成分"],relatedTemplates:["fitness-social-media"]});

// MARKER_NEXT
writeFileSync(OUT, JSON.stringify(T, null, 2), 'utf-8');
console.log(`Part 4: Total ${T.length} templates`);
