import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'data', 'templates.json');
const T = JSON.parse(readFileSync(OUT, 'utf-8'));

// === CLINIC (诊所中医馆) - 10 templates ===
T.push({id:"clinic-health-education",title:"诊所健康科普文案",slug:"clinic-health-education",industry:"clinic",task:"social-media",description:"为诊所生成健康科普类朋友圈内容",scenario:"日常发圈分享健康知识时使用",notFor:"不适合用于诊断建议或处方推荐",materialsNeeded:["科普主题","核心知识点","注意事项","免责提示"],prompt:"你是一位诊所健康科普文案助手。请生成一条科普内容。\n\n主题：{科普主题}\n知识点：{核心知识点}\n注意：{注意事项}\n\n要求：\n1. 字数60-100字\n2. 通俗易懂\n3. 必须包含「具体情况请咨询医生」的提示\n4. 不构成诊断或治疗建议\n5. 不推荐具体药物",fieldExplanations:{"科普主题":"如「春季过敏」「颈椎保健」","核心知识点":"想传达的健康知识","注意事项":"需要提醒的事项"},outputFormat:"60-100字科普文案（含免责提示）",exampleOutput:"春天花粉多，鼻子痒、打喷嚏的朋友注意：出门可以戴口罩，回家后洗脸洗鼻子，减少花粉接触。如果症状持续超过一周或影响睡眠，建议来看看，早期干预效果更好。（以上为一般性健康知识，不构成诊断建议，具体情况请咨询医生）（仅供格式参考）",reviewChecklist:["是否包含免责提示","无具体诊断建议","无药物推荐","知识是否准确"],relatedTemplates:["clinic-appointment","clinic-seasonal"]});
T.push({id:"clinic-appointment",title:"诊所预约提醒",slug:"clinic-appointment",industry:"clinic",task:"appointment",description:"为诊所生成预约确认和就诊提醒",scenario:"患者预约后确认、就诊前提醒时使用",notFor:"不适合用于紧急医疗通知",materialsNeeded:["患者称呼","预约科室","预约时间","就诊准备","诊所地址"],prompt:"你是一位诊所前台。请生成预约提醒话术。\n\n患者：{患者称呼}\n科室：{预约科室}\n时间：{预约时间}\n准备：{就诊准备}\n地址：{诊所地址}\n\n要求：\n1. 信息准确完整\n2. 语气温和专业\n3. 提醒就诊准备\n4. 字数60-100字",fieldExplanations:{"患者称呼":"患者怎么称呼","预约科室":"预约了什么科","预约时间":"就诊时间","就诊准备":"需要带什么或注意什么","诊所地址":"诊所位置"},outputFormat:"60-100字预约提醒",exampleOutput:"李阿姨您好，温馨提醒：您预约的明天（周三）上午9:30中医内科门诊已确认，接诊医生是张主任。就诊请带上之前的检查报告和正在服用的药物清单。地址：XX路XX号2楼。如需改期请提前联系我们（仅供格式参考）",reviewChecklist:["时间是否正确","科室信息准确","准备事项完整","语气是否专业"],relatedTemplates:["clinic-health-education","clinic-review-response"]});
T.push({id:"clinic-review-response",title:"诊所评价回复",slug:"clinic-review-response",industry:"clinic",task:"review-response",description:"为诊所线上评价生成回复",scenario:"收到平台评价时使用",notFor:"不适合用于医疗纠纷回应",materialsNeeded:["评价内容","评价星级","就诊科室","回复重点"],prompt:"你是一位诊所运营。请针对评价生成回复。\n\n评价：{评价内容}\n星级：{评价星级}\n科室：{就诊科室}\n重点：{回复重点}\n\n要求：\n1. 专业温和\n2. 不涉及具体病情\n3. 保护患者隐私\n4. 字数50-80字\n5. 差评要表示重视",fieldExplanations:{"评价内容":"患者写的评价","评价星级":"几星","就诊科室":"看的什么科","回复重点":"想强调什么"},outputFormat:"50-80字评价回复",exampleOutput:"感谢您的信任和反馈！很高兴我们的服务让您感到满意。后续如有任何健康问题，欢迎随时预约咨询。祝您身体健康，生活愉快（仅供格式参考）",reviewChecklist:["无涉及病情","无隐私泄露","语气是否专业","差评是否表示重视"],relatedTemplates:["clinic-appointment","clinic-brand-story"]});
T.push({id:"clinic-seasonal",title:"诊所季节性健康提醒",slug:"clinic-seasonal",industry:"clinic",task:"seasonal-promo",description:"为诊所生成季节性健康提醒和体检推广",scenario:"换季健康提醒、体检季推广时使用",notFor:"不适合用于疾病诊断",materialsNeeded:["季节主题","健康提醒","服务推荐","免责说明"],prompt:"你是一位诊所健康宣传助手。请生成季节性内容。\n\n主题：{季节主题}\n提醒：{健康提醒}\n服务：{服务推荐}\n\n要求：\n1. 字数80-120字\n2. 以科普为主\n3. 必须包含免责提示\n4. 不构成诊断建议\n5. 不制造健康焦虑",fieldExplanations:{"季节主题":"如「秋冬养生」「春季过敏」","健康提醒":"季节性健康建议","服务推荐":"诊所相关服务"},outputFormat:"80-120字季节性内容（含免责）",exampleOutput:"入秋了，提醒大家注意几点：1.早晚温差大，注意增减衣物；2.空气干燥，多喝水多吃润肺食物；3.老年人关节容易不适，注意保暖。我们诊所本月推出秋季体检套餐，含基础检查+中医体质辨识，适合想了解自己身体状况的朋友。（以上为一般性建议，不构成医疗诊断，具体健康问题请就医咨询）（仅供格式参考）",reviewChecklist:["是否含免责提示","无诊断建议","无焦虑营销","建议是否合理"],relatedTemplates:["clinic-health-education","clinic-appointment"]});
T.push({id:"clinic-complaint",title:"诊所投诉处理",slug:"clinic-complaint",industry:"clinic",task:"complaint-handling",description:"为诊所患者投诉生成处理话术",scenario:"患者投诉等候时间、服务态度等问题时使用",notFor:"不适合用于医疗事故处理",materialsNeeded:["投诉内容","核实情况","解决方案","改进措施"],prompt:"你是一位诊所负责人。请针对投诉生成处理话术。\n\n投诉：{投诉内容}\n情况：{核实情况}\n方案：{解决方案}\n改进：{改进措施}\n\n要求：\n1. 诚恳道歉\n2. 重视患者感受\n3. 给出改进方案\n4. 不涉及具体病情\n5. 字数80-120字",fieldExplanations:{"投诉内容":"患者投诉什么","核实情况":"实际情况","解决方案":"如何解决","改进措施":"如何改进"},outputFormat:"80-120字投诉处理话术",exampleOutput:"您好，非常抱歉给您带来了不好的就诊体验。关于等候时间过长的问题，当天确实因为临时加号导致排队延长，是我们预约管理不够合理。已做调整：1.严格控制每日加号数量；2.等候超过30分钟主动告知预计时间。感谢您的反馈，这对我们改进服务很重要（仅供格式参考）",reviewChecklist:["是否诚恳道歉","方案是否具体","无涉及病情","改进是否可行"],relatedTemplates:["clinic-review-response","clinic-appointment"]});
T.push({id:"clinic-brand-story",title:"诊所品牌介绍",slug:"clinic-brand-story",industry:"clinic",task:"brand-story",description:"为诊所撰写品牌介绍",scenario:"更新官网、平台介绍时使用",notFor:"不适合用于医疗广告",materialsNeeded:["创办背景","医疗理念","团队介绍","服务特色"],prompt:"你是一位医疗品牌文案助手。请为诊所撰写品牌介绍。\n\n背景：{创办背景}\n理念：{医疗理念}\n团队：{团队介绍}\n特色：{服务特色}\n\n要求：\n1. 字数150-250字\n2. 专业可信\n3. 不夸大疗效\n4. 包含资质说明\n5. 适合官网展示",fieldExplanations:{"创办背景":"诊所的创办历史","医疗理念":"怎么看待医疗服务","团队介绍":"医生团队背景","服务特色":"和其他诊所的区别"},outputFormat:"150-250字品牌介绍（含免责）",exampleOutput:"本诊所成立于2018年，由三位从三甲医院出来的中医师联合创办。我们的理念是：让看中医变得简单、透明、不神秘。每位医师都有10年以上临床经验，擅长领域各有不同。我们坚持：望闻问切不省略、用药剂量透明公开、治疗方案充分沟通。不夸大疗效，不过度治疗。诊所虽小，但每一味药材都经过严格把控。（本介绍仅供了解诊所背景，不构成医疗效果承诺）（仅供格式参考）",reviewChecklist:["资质描述是否真实","无疗效承诺","是否含免责","团队介绍是否准确"],relatedTemplates:["clinic-health-education"]});

// === AUTO-REPAIR (汽车服务) - 10 templates ===
T.push({id:"auto-repair-service-intro",title:"汽车服务项目介绍",slug:"auto-repair-service-intro",industry:"auto-repair",task:"product-description",description:"为汽修店服务项目撰写介绍",scenario:"更新价目表、上线团购平台时使用",notFor:"不适合用于保险理赔说明",materialsNeeded:["服务名称","服务内容","适用车型","价格","耗时"],prompt:"你是一位汽车服务文案助手。请为以下服务撰写介绍。\n\n服务：{服务名称}\n内容：{服务内容}\n车型：{适用车型}\n价格：{价格}\n耗时：{耗时}\n\n要求：\n1. 字数80-120字\n2. 专业透明\n3. 价格明确\n4. 不夸大效果\n5. 适合美团/抖音展示",fieldExplanations:{"服务名称":"如「小保养」「全车精洗」","服务内容":"具体做什么","适用车型":"什么车适合","价格":"收费标准","耗时":"大约多久"},outputFormat:"80-120字服务介绍",exampleOutput:"【小保养套餐】包含：更换机油（全合成）+机滤+全车检查（刹车、轮胎、灯光等20项）。适用：5万公里以内各品牌轿车/SUV。价格：399元起（含工时+材料），不同机油品牌价格略有差异，到店报价。耗时约45分钟，可在休息区等候。提前预约不用排队（仅供格式参考）",reviewChecklist:["价格是否准确","服务内容是否完整","适用范围是否清晰","无夸大效果"],relatedTemplates:["auto-repair-quotation","auto-repair-social-media"]});
T.push({id:"auto-repair-quotation",title:"汽修报价说明",slug:"auto-repair-quotation",industry:"auto-repair",task:"quotation",description:"为汽修店生成维修报价说明",scenario:"检查后向车主报价时使用",notFor:"不适合用于保险定损",materialsNeeded:["车辆信息","故障描述","维修方案","费用明细","质保说明"],prompt:"你是一位汽修店技师。请生成维修报价说明。\n\n车辆：{车辆信息}\n故障：{故障描述}\n方案：{维修方案}\n费用：{费用明细}\n质保：{质保说明}\n\n要求：\n1. 费用分项透明\n2. 方案说明清晰\n3. 包含质保信息\n4. 语气专业\n5. 字数100-150字",fieldExplanations:{"车辆信息":"车型和年份","故障描述":"检查发现的问题","维修方案":"怎么修","费用明细":"配件费+工时费","质保说明":"修完保多久"},outputFormat:"100-150字报价说明",exampleOutput:"张先生您好，您的2020款卡罗拉检查结果如下：\n故障：刹车片磨损严重（剩余厚度不足2mm），建议更换\n方案：更换前轮刹车片一对\n费用：刹车片（原厂件）280元+工时费80元=合计360元\n质保：配件质保1年或2万公里\n建议尽快更换，目前制动距离已经偏长。如同意方案，今天1小时内可完成（仅供格式参考）",reviewChecklist:["费用是否透明","方案是否合理","质保是否明确","无隐藏收费"],relatedTemplates:["auto-repair-service-intro","auto-repair-customer-comm"]});
T.push({id:"auto-repair-customer-comm",title:"汽修客户沟通话术",slug:"auto-repair-customer-comm",industry:"auto-repair",task:"customer-service",description:"为汽修店生成与车主沟通的话术",scenario:"维修进度通知、取车提醒时使用",notFor:"不适合用于事故责任认定",materialsNeeded:["车主称呼","维修项目","当前进度","预计完成时间"],prompt:"你是一位汽修店客服。请生成客户沟通话术。\n\n车主：{车主称呼}\n项目：{维修项目}\n进度：{当前进度}\n完成：{预计完成时间}\n\n要求：\n1. 信息明确\n2. 语气专业友好\n3. 主动告知进度\n4. 字数50-80字",fieldExplanations:{"车主称呼":"车主怎么称呼","维修项目":"在修什么","当前进度":"修到哪一步了","预计完成时间":"什么时候能取车"},outputFormat:"50-80字沟通话术",exampleOutput:"王哥您好，您的车刹车片已经换好了，现在在做最后的制动测试。一切正常的话，下午3点左右可以来取车。取车时我给您演示一下新刹车片的磨合注意事项。到时候直接来就行（仅供格式参考）",reviewChecklist:["进度信息是否准确","时间是否合理","语气是否专业","信息是否完整"],relatedTemplates:["auto-repair-quotation","auto-repair-review-response"]});
T.push({id:"auto-repair-review-response",title:"汽修店评价回复",slug:"auto-repair-review-response",industry:"auto-repair",task:"review-response",description:"为汽修店线上评价生成回复",scenario:"收到平台评价时使用",notFor:"不适合用于纠纷处理",materialsNeeded:["评价内容","评价星级","服务项目","回复重点"],prompt:"你是一位汽修店运营。请针对评价生成回复。\n\n评价：{评价内容}\n星级：{评价星级}\n服务：{服务项目}\n重点：{回复重点}\n\n要求：\n1. 专业可信\n2. 针对具体内容\n3. 体现技术实力\n4. 字数50-80字",fieldExplanations:{"评价内容":"车主写的评价","评价星级":"几星","服务项目":"做了什么服务","回复重点":"想强调什么"},outputFormat:"50-80字评价回复",exampleOutput:"感谢王哥的认可！刹车系统关乎安全，我们一直用原厂件+标准工艺，就是为了让车主放心。新刹车片磨合期注意轻踩，200公里后就完全正常了。后续有任何问题随时来，质保期内免费检查（仅供格式参考）",reviewChecklist:["语气是否专业","回复是否具体","质保信息准确","无过度承诺"],relatedTemplates:["auto-repair-customer-comm","auto-repair-social-media"]});
T.push({id:"auto-repair-social-media",title:"汽修店朋友圈内容",slug:"auto-repair-social-media",industry:"auto-repair",task:"social-media",description:"为汽修店生成朋友圈日常内容",scenario:"日常发圈分享用车知识、展示工作时使用",notFor:"不适合用于虚假案例",materialsNeeded:["今日内容","用车知识","工作展示"],prompt:"你是一位汽修师傅的朋友圈运营助手。请生成日常内容。\n\n内容：{今日内容}\n知识：{用车知识}\n展示：{工作展示}\n\n要求：\n1. 字数50-80字\n2. 实用有料\n3. 展示专业性\n4. 不恐吓营销\n5. 适合配工作照",fieldExplanations:{"今日内容":"今天想分享什么","用车知识":"实用的用车小贴士","工作展示":"今天的工作内容"},outputFormat:"50-80字朋友圈文案",exampleOutput:"今天接了一台5年没换过刹车油的车，踩刹车明显发软。提醒大家：刹车油建议每2年或4万公里更换一次，时间长了会吸水导致沸点降低，影响制动效果。这个保养项目不贵但很重要，别忽略了（仅供格式参考）",reviewChecklist:["知识是否准确","无恐吓营销","语气是否自然","无过度推销"],relatedTemplates:["auto-repair-service-intro","auto-repair-seasonal"]});
T.push({id:"auto-repair-seasonal",title:"汽修季节性保养提醒",slug:"auto-repair-seasonal",industry:"auto-repair",task:"seasonal-promo",description:"为汽修店生成季节性保养提醒和优惠",scenario:"换季保养提醒、节前检车活动时使用",notFor:"不适合用于强制消费",materialsNeeded:["季节主题","保养建议","优惠活动","预约方式"],prompt:"你是一位汽修店营销助手。请生成季节性保养提醒。\n\n主题：{季节主题}\n建议：{保养建议}\n优惠：{优惠活动}\n预约：{预约方式}\n\n要求：\n1. 字数80-120字\n2. 实用建议为主\n3. 不恐吓营销\n4. 优惠信息清晰\n5. 适合朋友圈",fieldExplanations:{"季节主题":"如「入冬检车」「长假前检查」","保养建议":"季节性保养建议","优惠活动":"有什么优惠","预约方式":"怎么预约"},outputFormat:"80-120字季节性文案",exampleOutput:"国庆准备自驾出行的朋友，出发前建议做个全车检查：轮胎气压和磨损、刹车系统、机油液位、灯光。本月推出「出行安检套餐」：全车20项检查+胎压调整+玻璃水加注，只收工时费50元。发现问题再报价，不强制消费。提前预约不排队，电话/微信都行（仅供格式参考）",reviewChecklist:["建议是否合理","无恐吓营销","优惠信息准确","无强制消费"],relatedTemplates:["auto-repair-social-media","auto-repair-service-intro"]});
T.push({id:"auto-repair-complaint",title:"汽修投诉处理",slug:"auto-repair-complaint",industry:"auto-repair",task:"complaint-handling",description:"为汽修店客户投诉生成处理话术",scenario:"车主投诉维修质量、收费等问题时使用",notFor:"不适合用于法律纠纷",materialsNeeded:["投诉内容","核实情况","解决方案","质保处理"],prompt:"你是一位汽修店店长。请针对投诉生成处理话术。\n\n投诉：{投诉内容}\n情况：{核实情况}\n方案：{解决方案}\n质保：{质保处理}\n\n要求：\n1. 诚恳负责\n2. 技术说明清晰\n3. 质保承诺明确\n4. 字数80-120字",fieldExplanations:{"投诉内容":"车主投诉什么","核实情况":"检查后的实际情况","解决方案":"如何解决","质保处理":"质保范围内如何处理"},outputFormat:"80-120字投诉处理话术",exampleOutput:"王哥您好，关于您反映的换完刹车片后有异响的问题，我刚才检查了一下，是新刹车片还在磨合期，属于正常现象，一般跑200-300公里就会消失。但为了让您放心，我再帮您做一次制动系统全面检查，确认没有其他问题。如果300公里后还有异响，随时来，质保期内免费处理（仅供格式参考）",reviewChecklist:["技术说明是否准确","态度是否诚恳","质保是否明确","方案是否合理"],relatedTemplates:["auto-repair-review-response","auto-repair-customer-comm"]});
T.push({id:"auto-repair-brand-story",title:"汽修店品牌介绍",slug:"auto-repair-brand-story",industry:"auto-repair",task:"brand-story",description:"为汽修店撰写品牌介绍",scenario:"更新平台店铺介绍时使用",notFor:"不适合用于资质申报",materialsNeeded:["从业经历","经营理念","技术特色","服务承诺"],prompt:"你是一位品牌文案助手。请为汽修店撰写品牌介绍。\n\n经历：{从业经历}\n理念：{经营理念}\n技术：{技术特色}\n承诺：{服务承诺}\n\n要求：\n1. 字数120-200字\n2. 突出技术和诚信\n3. 真实可信\n4. 适合平台展示",fieldExplanations:{"从业经历":"做了多少年","经营理念":"怎么看待汽修","技术特色":"擅长什么","服务承诺":"对车主的承诺"},outputFormat:"120-200字品牌介绍",exampleOutput:"干汽修15年了，从4S店出来自己开店已经8年。开店的原因很简单：想让车主修车不被坑。我们的原则：检查免费、报价透明、不过度维修。能修的不换，能用副厂件解决的不强推原厂。所有配件明码标价，工时费单独列出。团队5个技师都有5年以上经验，擅长底盘和发动机。修完车都有质保，质保期内同一问题免费返修（仅供格式参考）",reviewChecklist:["经历是否真实","承诺是否可兑现","无夸大宣传","资质描述准确"],relatedTemplates:["auto-repair-social-media"]});

// MARKER_NEXT
writeFileSync(OUT, JSON.stringify(T, null, 2), 'utf-8');
console.log(`Part 6: Total ${T.length} templates`);
