import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'data', 'templates.json');
const T = JSON.parse(readFileSync(OUT, 'utf-8'));

// === PHOTOGRAPHY (摄影工作室) - 10 templates ===
T.push({id:"photography-package-intro",title:"摄影套餐介绍",slug:"photography-package-intro",industry:"photography",task:"product-description",description:"为摄影工作室套餐撰写介绍文案",scenario:"更新官网、发朋友圈推广套餐时使用",notFor:"不适合用于合同条款",materialsNeeded:["套餐名称","包含内容","拍摄风格","价格","适合人群"],prompt:"你是一位摄影工作室文案助手。请为以下套餐撰写介绍。\n\n套餐名称：{套餐名称}\n包含内容：{包含内容}\n拍摄风格：{拍摄风格}\n价格：{价格}\n适合人群：{适合人群}\n\n要求：\n1. 字数100-150字\n2. 突出拍摄体验和成片效果\n3. 不承诺具体张数以外的效果\n4. 语气文艺但不做作\n5. 适合小红书或朋友圈",fieldExplanations:{"套餐名称":"如「轻写真套餐」「全家福套餐」","包含内容":"几套服装、多少精修、是否含妆造","拍摄风格":"如「日系清新」「复古胶片」","价格":"套餐价格","适合人群":"什么人适合拍"},outputFormat:"100-150字套餐介绍",exampleOutput:"【日系轻写真套餐】适合想留下自然状态的你。包含：1套服装拍摄+专业妆造+15张精修+全部底片。拍摄风格以自然光为主，不过度修图，保留真实的你。室内/户外可选，全程约2小时，轻松不累。价格：899元。适合闺蜜、情侣、个人写真。提前一周预约，可选周末或工作日（仅供格式参考）",reviewChecklist:["包含内容是否清晰","价格是否准确","无过度承诺","风格描述是否准确"],relatedTemplates:["photography-campaign","photography-social-media"]});
T.push({id:"photography-campaign",title:"摄影活动促销文案",slug:"photography-campaign",industry:"photography",task:"campaign-copy",description:"为摄影工作室促销活动撰写文案",scenario:"节日促销、周年庆、限时优惠时使用",notFor:"不适合用于虚假降价",materialsNeeded:["活动主题","优惠内容","活动时间","预约方式"],prompt:"你是一位摄影工作室营销助手。请撰写活动文案。\n\n主题：{活动主题}\n优惠：{优惠内容}\n时间：{活动时间}\n预约：{预约方式}\n\n要求：\n1. 字数80-120字\n2. 营造限时感\n3. 不虚假降价\n4. 适合朋友圈\n5. 文艺但接地气",fieldExplanations:{"活动主题":"如「春日限定」「周年庆」","优惠内容":"具体优惠","活动时间":"起止日期","预约方式":"怎么预约"},outputFormat:"80-120字活动文案",exampleOutput:"春日限定写真开拍！3月樱花季，我们在公园踩好了点位。本月预约户外写真套餐，加赠5张精修（原套餐15张→20张），不加价。限10组名额，拍完这季花期就结束了。想在春天留下好看照片的姐妹，微信预约选时间段（仅供格式参考）",reviewChecklist:["优惠是否真实","时间是否正确","名额限制是否合理","无虚假宣传"],relatedTemplates:["photography-package-intro","photography-seasonal"]});
T.push({id:"photography-social-media",title:"摄影工作室朋友圈",slug:"photography-social-media",industry:"photography",task:"social-media",description:"为摄影工作室生成朋友圈日常内容",scenario:"日常发圈展示客片、分享拍摄花絮时使用",notFor:"不适合用于未经客户同意的照片展示",materialsNeeded:["今日内容","拍摄花絮","摄影小知识"],prompt:"你是一位摄影师的朋友圈运营助手。请生成日常内容。\n\n内容：{今日内容}\n花絮：{拍摄花絮}\n知识：{摄影小知识}\n\n要求：\n1. 字数40-70字\n2. 展示审美和专业\n3. 不过度修饰\n4. 适合配客片发布\n5. 需客户同意后才发",fieldExplanations:{"今日内容":"今天想分享什么","拍摄花絮":"拍摄中的有趣事","摄影小知识":"可以分享的拍照技巧"},outputFormat:"40-70字朋友圈文案",exampleOutput:"今天拍的这组闺蜜写真，两个人从头笑到尾，自然的表情比摆拍好看一百倍。其实拍照不用紧张，聊着天就拍完了。（已获客户授权展示）（仅供格式参考）",reviewChecklist:["是否获得客户授权","语气是否自然","无过度修饰","无隐私泄露"],relatedTemplates:["photography-package-intro","photography-short-video"]});
T.push({id:"photography-short-video",title:"摄影工作室短视频脚本",slug:"photography-short-video",industry:"photography",task:"short-video",description:"为摄影工作室短视频撰写脚本",scenario:"拍摄幕后花絮、成片展示、拍照教程时使用",notFor:"不适合用于未授权的客户视频",materialsNeeded:["视频主题","展示内容","目标受众","时长"],prompt:"你是一位摄影短视频策划。请撰写脚本。\n\n主题：{视频主题}\n内容：{展示内容}\n受众：{目标受众}\n时长：{时长}\n\n要求：\n1. 视觉冲击力强\n2. 展示前后对比\n3. 适合竖屏\n4. 需客户授权\n5. 分镜头描述",fieldExplanations:{"视频主题":"如「拍摄花絮」「修图前后」","展示内容":"具体展示什么","目标受众":"想吸引什么客户","时长":"视频时长"},outputFormat:"分镜头脚本",exampleOutput:"【开场2秒】画面：相机快门声+闪光灯。字幕「今日份客片出炉」\n【中间12秒】画面：拍摄花絮（摄影师指导动作）→ 原片 → 精修成片对比。配轻音乐\n【结尾3秒】画面：多张成片快速切换。字幕「想拍同款？私信预约」（仅供格式参考）",reviewChecklist:["是否获得客户授权","拍摄方案可执行","无过度美化","无虚假展示"],relatedTemplates:["photography-social-media","photography-campaign"]});
T.push({id:"photography-appointment",title:"摄影预约确认",slug:"photography-appointment",industry:"photography",task:"appointment",description:"为摄影工作室生成预约确认话术",scenario:"客户预约拍摄后确认细节时使用",notFor:"不适合用于合同签订",materialsNeeded:["客户称呼","拍摄套餐","拍摄时间","拍摄地点","准备事项"],prompt:"你是一位摄影工作室客服。请生成预约确认话术。\n\n客户：{客户称呼}\n套餐：{拍摄套餐}\n时间：{拍摄时间}\n地点：{拍摄地点}\n准备：{准备事项}\n\n要求：\n1. 信息完整\n2. 提醒准备事项\n3. 语气专业友好\n4. 字数80-120字",fieldExplanations:{"客户称呼":"客户怎么称呼","拍摄套餐":"预约了什么套餐","拍摄时间":"拍摄日期和时间","拍摄地点":"在哪里拍","准备事项":"客户需要准备什么"},outputFormat:"80-120字预约确认",exampleOutput:"小王您好～您的日系写真套餐预约已确认：本周六上午10点，地点在我们工作室（XX路XX号3楼）。温馨提示：1.当天含妆造，可以素颜来；2.建议带一双舒适的鞋子备用；3.如果有想拍的参考图可以提前发我。拍摄约2小时，轻松愉快。周六见（仅供格式参考）",reviewChecklist:["时间地点是否正确","准备事项是否完整","套餐信息准确","语气是否友好"],relatedTemplates:["photography-package-intro","photography-review-response"]});
T.push({id:"photography-review-response",title:"摄影评价回复",slug:"photography-review-response",industry:"photography",task:"review-response",description:"为摄影工作室线上评价生成回复",scenario:"收到大众点评等平台评价时使用",notFor:"不适合用于纠纷处理",materialsNeeded:["评价内容","评价星级","拍摄套餐","回复重点"],prompt:"你是一位摄影工作室运营。请针对评价生成回复。\n\n评价：{评价内容}\n星级：{评价星级}\n套餐：{拍摄套餐}\n重点：{回复重点}\n\n要求：\n1. 感谢客户信任\n2. 针对具体内容回应\n3. 语气真诚\n4. 字数50-80字",fieldExplanations:{"评价内容":"客户写的评价","评价星级":"几星","拍摄套餐":"拍了什么","回复重点":"想强调什么"},outputFormat:"50-80字评价回复",exampleOutput:"感谢小姐姐的好评！那天拍摄氛围确实很好，你本身就很上镜，加上自然光刚好，出片效果我们自己也很满意。精修照片已经发到你邮箱了，有任何修改需求随时说。期待下次合作（仅供格式参考）",reviewChecklist:["语气是否真诚","回复是否具体","无过度承诺","无泄露隐私"],relatedTemplates:["photography-social-media","photography-appointment"]});
T.push({id:"photography-seasonal",title:"摄影季节性活动",slug:"photography-seasonal",industry:"photography",task:"seasonal-promo",description:"为摄影工作室季节性主题活动撰写文案",scenario:"樱花季、秋景、圣诞等主题拍摄时使用",notFor:"不适合用于虚假场景宣传",materialsNeeded:["季节主题","拍摄场景","限定内容","活动时间"],prompt:"你是一位摄影营销助手。请撰写季节性活动文案。\n\n主题：{季节主题}\n场景：{拍摄场景}\n限定：{限定内容}\n时间：{活动时间}\n\n要求：\n1. 字数80-120字\n2. 营造季节氛围\n3. 突出限时性\n4. 适合小红书/朋友圈\n5. 文艺有质感",fieldExplanations:{"季节主题":"如「秋日银杏」「冬日暖阳」","拍摄场景":"在哪里拍","限定内容":"季节限定的特别内容","活动时间":"可预约的时间段"},outputFormat:"80-120字季节活动文案",exampleOutput:"秋天的银杏大道只美两周。我们踩好了三个绝佳点位，光线最好的时段是下午3-5点。本月推出「秋日限定」户外写真：含妆造+20张精修+全部底片，1299元。限15组，拍完这波黄叶就要等明年了。想在最美的季节留下照片的，现在可以约时间了（仅供格式参考）",reviewChecklist:["场景是否真实可达","时间是否准确","价格是否正确","无虚假宣传"],relatedTemplates:["photography-campaign","photography-package-intro"]});
T.push({id:"photography-membership",title:"摄影会员/年度套餐",slug:"photography-membership",industry:"photography",task:"membership",description:"为摄影工作室年度会员或多次套餐撰写推广",scenario:"推出年度拍摄计划、多次套餐时使用",notFor:"不适合用于合同条款",materialsNeeded:["套餐类型","包含次数","会员权益","价格对比"],prompt:"你是一位摄影工作室会员运营助手。请撰写套餐推广文案。\n\n类型：{套餐类型}\n次数：{包含次数}\n权益：{会员权益}\n对比：{价格对比}\n\n要求：\n1. 字数80-120字\n2. 突出性价比\n3. 适合有持续拍摄需求的客户\n4. 不强制推销\n5. 权益清晰",fieldExplanations:{"套餐类型":"如「年度记录计划」「亲子成长套餐」","包含次数":"一年拍几次","会员权益":"额外享受什么","价格对比":"和单次相比省多少"},outputFormat:"80-120字会员推广文案",exampleOutput:"给宝宝做个成长记录？「亲子年度套餐」：一年4次拍摄（每季度一次），每次含10张精修+全部底片。单次拍摄原价699，年度套餐2396元（相当于每次599，省400）。额外赠送：年底制作一本精装相册。适合想记录孩子每个阶段的家庭（仅供格式参考）",reviewChecklist:["价格计算是否正确","权益是否可兑现","无强制消费","适用人群是否明确"],relatedTemplates:["photography-package-intro","photography-campaign"]});
T.push({id:"photography-complaint",title:"摄影投诉处理",slug:"photography-complaint",industry:"photography",task:"complaint-handling",description:"为摄影工作室客户投诉生成处理话术",scenario:"客户对成片不满意、服务体验差时使用",notFor:"不适合用于法律纠纷",materialsNeeded:["投诉内容","核实情况","解决方案","补偿措施"],prompt:"你是一位摄影工作室负责人。请针对投诉生成处理话术。\n\n投诉：{投诉内容}\n情况：{核实情况}\n方案：{解决方案}\n补偿：{补偿措施}\n\n要求：\n1. 诚恳道歉\n2. 给出具体方案\n3. 尊重客户感受\n4. 字数80-120字",fieldExplanations:{"投诉内容":"客户不满意什么","核实情况":"实际情况","解决方案":"如何解决","补偿措施":"如何补偿"},outputFormat:"80-120字投诉处理话术",exampleOutput:"小姐姐您好，很抱歉这次的成片没有达到您的期望。看了您标注的几张照片，确实修图风格和您想要的有差距，是我们前期沟通不够充分。这样处理：这几张我重新精修，按您发的参考图风格来调。如果还是不满意，我们可以安排免费补拍一次。真的很抱歉，一定给您满意的结果（仅供格式参考）",reviewChecklist:["是否承认问题","方案是否具体","语气是否诚恳","补偿是否合理"],relatedTemplates:["photography-review-response","photography-appointment"]});
T.push({id:"photography-brand-story",title:"摄影工作室品牌故事",slug:"photography-brand-story",industry:"photography",task:"brand-story",description:"为摄影工作室撰写品牌介绍",scenario:"更新官网、社交媒体简介时使用",notFor:"不适合用于商业计划书",materialsNeeded:["创业故事","拍摄理念","风格特色","服务承诺"],prompt:"你是一位品牌文案助手。请为摄影工作室撰写品牌故事。\n\n故事：{创业故事}\n理念：{拍摄理念}\n风格：{风格特色}\n承诺：{服务承诺}\n\n要求：\n1. 字数150-250字\n2. 体现审美和态度\n3. 真实不做作\n4. 适合官网或小红书主页",fieldExplanations:{"创业故事":"为什么做摄影","拍摄理念":"怎么看待拍照这件事","风格特色":"擅长什么风格","服务承诺":"对客户的承诺"},outputFormat:"150-250字品牌故事",exampleOutput:"做摄影师五年了，最开始是给朋友拍着玩，后来发现自己真的喜欢用镜头记录人的状态。2021年租了个小工作室，就想做一件事：让每个来拍照的人都觉得轻松、自在，拍出来的是真实的自己而不是千篇一律的网红脸。我不追求过度精修，更喜欢抓拍自然的瞬间。每组客人我都会花时间聊天，了解你想要什么感觉，然后用我的方式帮你呈现。三年了，最开心的是很多客人变成了朋友，每年都会来拍一次（仅供格式参考）",reviewChecklist:["故事是否真实","理念是否清晰","无虚构成分","语气是否自然"],relatedTemplates:["photography-social-media"]});

// MARKER_NEXT
writeFileSync(OUT, JSON.stringify(T, null, 2), 'utf-8');
console.log(`Part 3: Total ${T.length} templates`);
