import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'data', 'templates.json');
const T = JSON.parse(readFileSync(OUT, 'utf-8'));

// === HOTEL (民宿酒店) - 10 templates ===
T.push({id:"hotel-room-description",title:"民宿房型介绍",slug:"hotel-room-description",industry:"hotel",task:"product-description",description:"为民宿/酒店房型撰写介绍文案",scenario:"上线OTA平台、更新官网时使用",notFor:"不适合用于虚假房源描述",materialsNeeded:["房型名称","房间配置","特色亮点","价格区间","入住须知"],prompt:"你是一位民宿文案助手。请为以下房型撰写介绍。\n\n房型：{房型名称}\n配置：{房间配置}\n亮点：{特色亮点}\n价格：{价格区间}\n须知：{入住须知}\n\n要求：\n1. 字数100-150字\n2. 突出体验感\n3. 配置信息准确\n4. 不夸大实际条件\n5. 适合携程/美团展示",fieldExplanations:{"房型名称":"如「山景大床房」「亲子套房」","房间配置":"床型、面积、设施","特色亮点":"最吸引人的点","价格区间":"淡旺季价格","入住须知":"入住退房时间等"},outputFormat:"100-150字房型介绍",exampleOutput:"【山景大床房】面积35平，落地窗正对茶山，早上拉开窗帘就是满眼绿色。配置：1.8m乳胶床垫、独立卫浴（干湿分离）、小冰箱、蓝牙音箱。免费提供茶具和本地茶叶，可以边泡茶边看山。价格：平日298，周末/节假日398。入住14:00后，退房12:00前。适合情侣或独自放松（仅供格式参考）",reviewChecklist:["配置描述是否准确","价格是否正确","入住须知是否完整","无夸大描述"],relatedTemplates:["hotel-review-response","hotel-social-media"]});
T.push({id:"hotel-review-response",title:"民宿评价回复",slug:"hotel-review-response",industry:"hotel",task:"review-response",description:"为民宿/酒店线上评价生成回复",scenario:"收到携程、美团等平台评价时使用",notFor:"不适合用于纠纷处理",materialsNeeded:["评价内容","评价星级","入住房型","回复重点"],prompt:"你是一位民宿运营。请针对评价生成回复。\n\n评价：{评价内容}\n星级：{评价星级}\n房型：{入住房型}\n重点：{回复重点}\n\n要求：\n1. 好评感谢，差评道歉\n2. 有温度有人情味\n3. 邀请再次入住\n4. 字数50-100字",fieldExplanations:{"评价内容":"客人写的评价","评价星级":"几星","入住房型":"住的什么房","回复重点":"想强调什么"},outputFormat:"50-100字评价回复",exampleOutput:"感谢您选择我们的民宿！很高兴您喜欢山景房的视野，那个角度看日出确实很美。下次来可以试试我们新开的露台烧烤，晚上看星星特别惬意。期待再次见到您，祝生活愉快（仅供格式参考）",reviewChecklist:["语气是否温暖","回复是否具体","无过度承诺","邀请是否自然"],relatedTemplates:["hotel-room-description","hotel-social-media"]});
T.push({id:"hotel-social-media",title:"民宿朋友圈内容",slug:"hotel-social-media",industry:"hotel",task:"social-media",description:"为民宿生成朋友圈日常内容",scenario:"日常发圈展示环境、分享住客故事时使用",notFor:"不适合用于虚假宣传",materialsNeeded:["今日内容","环境描述","住客故事"],prompt:"你是一位民宿主的朋友圈运营助手。请生成日常内容。\n\n内容：{今日内容}\n环境：{环境描述}\n故事：{住客故事}\n\n要求：\n1. 字数50-80字\n2. 有生活气息\n3. 展示真实环境\n4. 不过度美化\n5. 适合配实景照片",fieldExplanations:{"今日内容":"今天想分享什么","环境描述":"当前的环境状态","住客故事":"有趣的住客互动"},outputFormat:"50-80字朋友圈文案",exampleOutput:"今早雾气还没散，山间像铺了一层纱。昨天入住的一对小情侣，早上5点就起来等日出了，拍了好多照片。这种「特意早起看风景」的仪式感，大概就是旅行的意义吧（仅供格式参考）",reviewChecklist:["内容是否真实","无过度美化","语气是否自然","无隐私泄露"],relatedTemplates:["hotel-room-description","hotel-seasonal"]});
T.push({id:"hotel-seasonal",title:"民宿季节性推广",slug:"hotel-seasonal",industry:"hotel",task:"seasonal-promo",description:"为民宿季节性活动撰写推广文案",scenario:"节假日、旅游旺季、特色季节活动时使用",notFor:"不适合用于虚假降价",materialsNeeded:["季节主题","特色活动","优惠信息","预约方式"],prompt:"你是一位民宿营销助手。请撰写季节性推广文案。\n\n主题：{季节主题}\n活动：{特色活动}\n优惠：{优惠信息}\n预约：{预约方式}\n\n要求：\n1. 字数80-120字\n2. 营造度假氛围\n3. 突出季节特色\n4. 不虚假宣传\n5. 适合朋友圈/小红书",fieldExplanations:{"季节主题":"如「秋日赏枫」「冬日温泉」","特色活动":"季节限定的体验","优惠信息":"有什么优惠","预约方式":"怎么预约"},outputFormat:"80-120字季节推广文案",exampleOutput:"秋天的山里美得不像话，门口那排银杏已经全黄了。本月推出「秋日慢生活」套餐：住两晚送一晚，含每日早餐+下午茶+一次徒步向导。适合想远离城市、安静待几天的朋友。房间不多，周末基本满房，想来的建议提前一周预约。微信私聊我选房型（仅供格式参考）",reviewChecklist:["环境描述是否真实","优惠是否可兑现","预约方式是否畅通","无虚假宣传"],relatedTemplates:["hotel-social-media","hotel-room-description"]});
T.push({id:"hotel-complaint",title:"民宿投诉处理",slug:"hotel-complaint",industry:"hotel",task:"complaint-handling",description:"为民宿客人投诉生成处理话术",scenario:"客人投诉卫生、设施、噪音等问题时使用",notFor:"不适合用于安全事故处理",materialsNeeded:["投诉内容","核实情况","解决方案","补偿措施"],prompt:"你是一位民宿主。请针对客人投诉生成处理话术。\n\n投诉：{投诉内容}\n情况：{核实情况}\n方案：{解决方案}\n补偿：{补偿措施}\n\n要求：\n1. 诚恳道歉\n2. 快速解决\n3. 适当补偿\n4. 字数80-120字",fieldExplanations:{"投诉内容":"客人投诉什么","核实情况":"实际情况","解决方案":"如何解决","补偿措施":"如何补偿"},outputFormat:"80-120字投诉处理话术",exampleOutput:"您好，非常抱歉影响了您的入住体验。关于热水器水温不稳定的问题，我马上安排师傅来检修。在修好之前，我给您换到隔壁同等房型（热水正常），行李我帮您搬。另外今晚的房费给您减免100元作为补偿。再次说声抱歉，有任何问题随时找我（仅供格式参考）",reviewChecklist:["是否快速响应","方案是否具体","补偿是否合理","语气是否诚恳"],relatedTemplates:["hotel-review-response"]});
T.push({id:"hotel-appointment",title:"民宿入住引导",slug:"hotel-appointment",industry:"hotel",task:"appointment",description:"为民宿生成入住前引导话术",scenario:"客人预订后发送入住指引时使用",notFor:"不适合用于合同条款",materialsNeeded:["客人称呼","入住日期","房型","交通指引","入住须知"],prompt:"你是一位民宿管家。请生成入住引导话术。\n\n客人：{客人称呼}\n日期：{入住日期}\n房型：{房型}\n交通：{交通指引}\n须知：{入住须知}\n\n要求：\n1. 信息完整实用\n2. 语气温暖\n3. 包含交通指引\n4. 字数100-150字",fieldExplanations:{"客人称呼":"客人怎么称呼","入住日期":"什么时候来","房型":"订的什么房","交通指引":"怎么到达","入住须知":"需要注意什么"},outputFormat:"100-150字入住引导",exampleOutput:"王先生您好～欢迎预订我们的山景大床房！入住日期：本周六。几个实用信息：\n1. 导航搜「XX民宿」可直达，最后500米是山路，开慢点\n2. 入住时间14:00后，提前到可以先寄存行李\n3. 山里晚上凉，建议带件外套\n4. 我们提供免费停车位\n到了给我打电话，我在门口接您。有任何问题随时联系（仅供格式参考）",reviewChecklist:["交通信息是否准确","入住时间是否正确","须知是否完整","联系方式是否提供"],relatedTemplates:["hotel-room-description","hotel-review-response"]});
T.push({id:"hotel-membership",title:"民宿回头客优惠",slug:"hotel-membership",industry:"hotel",task:"membership",description:"为民宿老客户回头优惠撰写话术",scenario:"邀请住过的客人再次入住时使用",notFor:"不适合用于强制推销",materialsNeeded:["客人称呼","上次入住","回头优惠","新变化"],prompt:"你是一位民宿主。请生成老客户回头邀约话术。\n\n客人：{客人称呼}\n上次：{上次入住}\n优惠：{回头优惠}\n新变化：{新变化}\n\n要求：\n1. 语气像朋友\n2. 不强迫\n3. 分享新变化\n4. 字数60-100字",fieldExplanations:{"客人称呼":"客人怎么称呼","上次入住":"上次什么时候来的","回头优惠":"老客户有什么优惠","新变化":"民宿有什么新变化"},outputFormat:"60-100字回头邀约",exampleOutput:"小王好久不见～上次你们来还是夏天，现在秋天的山景完全不一样了，银杏全黄了特别美。最近新增了一个露台可以喝茶看山。老客户直接订享9折，周末也适用。有空带朋友再来坐坐？（仅供格式参考）",reviewChecklist:["语气是否自然","优惠是否真实","无强迫感","新变化是否真实"],relatedTemplates:["hotel-seasonal","hotel-social-media"]});
T.push({id:"hotel-brand-story",title:"民宿品牌故事",slug:"hotel-brand-story",industry:"hotel",task:"brand-story",description:"为民宿撰写品牌介绍",scenario:"更新OTA平台介绍、制作宣传册时使用",notFor:"不适合用于投资招商",materialsNeeded:["创业故事","选址原因","设计理念","服务特色"],prompt:"你是一位品牌文案助手。请为民宿撰写品牌故事。\n\n故事：{创业故事}\n选址：{选址原因}\n设计：{设计理念}\n服务：{服务特色}\n\n要求：\n1. 字数150-250字\n2. 有情怀有温度\n3. 真实不做作\n4. 适合OTA平台展示",fieldExplanations:{"创业故事":"为什么开民宿","选址原因":"为什么选这个地方","设计理念":"装修风格和理念","服务特色":"和别家有什么不同"},outputFormat:"150-250字品牌故事",exampleOutput:"在城里工作了十年，每次周末往山里跑都觉得时间太短。2021年索性辞了职，在这个小村子租了栋老房子，花了半年时间改造成现在的样子。选这里是因为安静——没有商业街，出门就是茶山和竹林。房间不多，只有5间，每间都能看到不同的风景。我不想做标准化的酒店，就想做一个「朋友来了会觉得舒服」的地方。早餐是我自己做的，用的都是村里的食材。很多客人说，来这里最大的感受是「终于可以什么都不想了」（仅供格式参考）",reviewChecklist:["故事是否真实","环境描述是否准确","无虚构成分","语气是否自然"],relatedTemplates:["hotel-social-media"]});
T.push({id:"hotel-short-video",title:"民宿短视频脚本",slug:"hotel-short-video",industry:"hotel",task:"short-video",description:"为民宿短视频撰写脚本",scenario:"拍摄环境展示、入住体验类视频时使用",notFor:"不适合用于虚假场景展示",materialsNeeded:["视频主题","拍摄场景","想传达的感觉","时长"],prompt:"你是一位民宿短视频策划。请撰写脚本。\n\n主题：{视频主题}\n场景：{拍摄场景}\n感觉：{想传达的感觉}\n时长：{时长}\n\n要求：\n1. 展示真实环境\n2. 营造氛围感\n3. 适合竖屏\n4. 不过度美化\n5. 分镜头描述",fieldExplanations:{"视频主题":"如「一天的生活」「房间展示」","拍摄场景":"拍哪些地方","想传达的感觉":"如「安静」「治愈」","时长":"视频时长"},outputFormat:"分镜头脚本",exampleOutput:"【开场5秒】画面：清晨薄雾中的民宿外观，鸟叫声。无字幕，只有环境音\n【中间20秒】画面：推开房门→落地窗外的山景→泡一杯茶→坐在露台发呆。配轻柔钢琴BGM\n【结尾5秒】画面：夕阳下的全景。字幕「有时候，什么都不做也是一种奢侈」（仅供格式参考）",reviewChecklist:["环境是否真实","无过度美化","拍摄方案可执行","氛围是否到位"],relatedTemplates:["hotel-social-media","hotel-room-description"]});
T.push({id:"hotel-recruitment",title:"民宿招聘启事",slug:"hotel-recruitment",industry:"hotel",task:"recruitment",description:"为民宿招聘管家或保洁",scenario:"招聘民宿管家、保洁阿姨时使用",notFor:"不适合用于高管招聘",materialsNeeded:["招聘岗位","工作内容","薪资待遇","工作环境"],prompt:"你是一位民宿人事助手。请撰写招聘启事。\n\n岗位：{招聘岗位}\n内容：{工作内容}\n薪资：{薪资待遇}\n环境：{工作环境}\n\n要求：\n1. 突出工作环境好\n2. 薪资透明\n3. 语气友好\n4. 字数100-150字",fieldExplanations:{"招聘岗位":"如「民宿管家」「保洁」","工作内容":"日常做什么","薪资待遇":"薪资结构","工作环境":"工作环境描述"},outputFormat:"100-150字招聘启事",exampleOutput:"【招聘民宿管家1名】\n工作：接待客人、日常维护、协助早餐准备\n薪资：4500-5500/月，包吃住（住在民宿里）\n时间：做五休二，旺季可能加班（有加班费）\n要求：性格开朗、爱干净、会基本沟通\n环境：在山里，空气好，节奏慢\n适合喜欢安静生活、不想在城里卷的朋友。有兴趣先来住两天体验一下（仅供格式参考）",reviewChecklist:["薪资是否真实","工作内容是否清晰","环境描述准确","无歧视性用语"],relatedTemplates:["hotel-brand-story"]});

// MARKER_NEXT
writeFileSync(OUT, JSON.stringify(T, null, 2), 'utf-8');
console.log(`Part 5: Total ${T.length} templates`);
