import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'data', 'templates.json');
const T = JSON.parse(readFileSync(OUT, 'utf-8'));

// === FLOWER (花店绿植) - 8 templates ===
T.push({id:"flower-product-desc",title:"花束产品描述",slug:"flower-product-desc",industry:"flower",task:"product-description",description:"为花店花束/绿植撰写产品描述",scenario:"上线美团、小红书展示时使用",notFor:"不适合用于批发报价",materialsNeeded:["花束名称","花材组成","适合场景","价格","养护建议"],prompt:"你是一位花店文案助手。请为以下花束撰写描述。\n\n名称：{花束名称}\n花材：{花材组成}\n场景：{适合场景}\n价格：{价格}\n养护：{养护建议}\n\n要求：\n1. 字数80-120字\n2. 有美感和仪式感\n3. 说明花材和养护\n4. 不夸大花期\n5. 适合电商展示",fieldExplanations:{"花束名称":"花束的名字","花材组成":"用了什么花","适合场景":"送什么人/什么场合","价格":"售价","养护建议":"怎么养护延长花期"},outputFormat:"80-120字产品描述",exampleOutput:"【晨光系列·暖阳】主花材：香槟玫瑰5枝+洋桔梗+尤加利叶，暖色调搭配，温柔不张扬。适合送闺蜜、送自己、或者摆在家里提升氛围。价格：128元（含包装）。收到后斜切根部，换清水+保鲜剂，避免阳光直射，正常花期5-7天。每周三到新鲜花材，建议提前一天预订（仅供格式参考）",reviewChecklist:["花材描述是否准确","价格是否正确","养护建议是否实用","无夸大花期"],relatedTemplates:["flower-campaign","flower-social-media"]});
T.push({id:"flower-campaign",title:"花店节日促销文案",slug:"flower-campaign",industry:"flower",task:"seasonal-promo",description:"为花店节日活动撰写促销文案",scenario:"情人节、母亲节、七夕等节日促销时使用",notFor:"不适合用于丧葬花圈",materialsNeeded:["节日主题","活动内容","限定花束","预订方式"],prompt:"你是一位花店营销助手。请撰写节日促销文案。\n\n节日：{节日主题}\n活动：{活动内容}\n限定：{限定花束}\n预订：{预订方式}\n\n要求：\n1. 字数80-120字\n2. 营造节日氛围\n3. 突出限量/限时\n4. 不过度煽情\n5. 适合朋友圈",fieldExplanations:{"节日主题":"什么节日","活动内容":"有什么优惠","限定花束":"节日限定款","预订方式":"怎么预订"},outputFormat:"80-120字节日文案",exampleOutput:"母亲节快到了，今年想送妈妈一束花吗？我们准备了三款母亲节限定花束：康乃馨系列（99/168/268元），每款都搭配了手写贺卡。5.10-5.12期间下单，免费同城配送。限量50束，去年中午就卖完了，想送的建议提前预订。微信发我选款+地址就行（仅供格式参考）",reviewChecklist:["节日信息是否正确","价格是否准确","限量是否真实","配送范围是否说明"],relatedTemplates:["flower-product-desc","flower-social-media"]});
T.push({id:"flower-social-media",title:"花店朋友圈内容",slug:"flower-social-media",industry:"flower",task:"social-media",description:"为花店生成朋友圈日常内容",scenario:"日常发圈展示花艺、分享养花知识时使用",notFor:"不适合用于广告投放",materialsNeeded:["今日花材","花艺分享","养花知识"],prompt:"你是一位花店老板的朋友圈运营助手。请生成日常内容。\n\n花材：{今日花材}\n分享：{花艺分享}\n知识：{养花知识}\n\n要求：\n1. 字数40-70字\n2. 有美感\n3. 可以带养花小贴士\n4. 不硬推销\n5. 适合配花艺照片",fieldExplanations:{"今日花材":"今天到了什么花","花艺分享":"今天做了什么花艺","养花知识":"实用的养花建议"},outputFormat:"40-70字朋友圈文案",exampleOutput:"今天到了一批芍药，花苞饱满，养两天就会慢慢打开，特别治愈。芍药花期不长但很美，建议每天换水+斜切根部，能多开几天。想要的姐妹私我留，明天就没这么新鲜了（仅供格式参考）",reviewChecklist:["内容是否真实","语气是否自然","知识是否准确","无过度推销"],relatedTemplates:["flower-product-desc","flower-campaign"]});
T.push({id:"flower-review-response",title:"花店评价回复",slug:"flower-review-response",industry:"flower",task:"review-response",description:"为花店线上评价生成回复",scenario:"收到美团等平台评价时使用",notFor:"不适合用于纠纷处理",materialsNeeded:["评价内容","评价星级","购买产品","回复重点"],prompt:"你是一位花店运营。请针对评价生成回复。\n\n评价：{评价内容}\n星级：{评价星级}\n产品：{购买产品}\n重点：{回复重点}\n\n要求：\n1. 温暖有美感\n2. 针对具体内容\n3. 可以附养护建议\n4. 字数50-80字",fieldExplanations:{"评价内容":"客户写的评价","评价星级":"几星","购买产品":"买了什么","回复重点":"想强调什么"},outputFormat:"50-80字评价回复",exampleOutput:"感谢喜欢！这款香槟玫瑰确实很温柔，搭配尤加利叶特别有质感。收到后记得每天换水，放在通风阴凉处，花期会更长。下次有新花材到货我朋友圈会更新，喜欢的话可以关注一下（仅供格式参考）",reviewChecklist:["语气是否温暖","回复是否具体","养护建议是否实用","无过度承诺"],relatedTemplates:["flower-social-media","flower-product-desc"]});
T.push({id:"flower-complaint",title:"花店投诉处理",slug:"flower-complaint",industry:"flower",task:"complaint-handling",description:"为花店客户投诉生成处理话术",scenario:"客户投诉花材不新鲜、配送损坏等问题时使用",notFor:"不适合用于批量退货",materialsNeeded:["投诉内容","核实情况","解决方案","补偿措施"],prompt:"你是一位花店老板。请针对投诉生成处理话术。\n\n投诉：{投诉内容}\n情况：{核实情况}\n方案：{解决方案}\n补偿：{补偿措施}\n\n要求：\n1. 诚恳道歉\n2. 快速解决\n3. 适当补偿\n4. 字数80-120字",fieldExplanations:{"投诉内容":"客户投诉什么","核实情况":"实际情况","解决方案":"如何解决","补偿措施":"如何补偿"},outputFormat:"80-120字投诉处理话术",exampleOutput:"亲，非常抱歉！看了您发的照片，确实有两枝玫瑰在运输过程中折损了，这是我们包装不够到位的问题。给您两个方案：1.今天重新配送一束新的给您；2.退还折损部分的费用+赠送下次购花8折券。您看哪个方便？再次说声抱歉（仅供格式参考）",reviewChecklist:["是否承认问题","方案是否具体","补偿是否合理","语气是否诚恳"],relatedTemplates:["flower-review-response"]});
T.push({id:"flower-membership",title:"花店订阅/会员推广",slug:"flower-membership",industry:"flower",task:"membership",description:"为花店鲜花订阅或会员制度撰写推广",scenario:"推出每周鲜花订阅、会员卡时使用",notFor:"不适合用于合同条款",materialsNeeded:["订阅类型","频次价格","会员权益","适合人群"],prompt:"你是一位花店会员运营助手。请撰写订阅/会员推广文案。\n\n类型：{订阅类型}\n价格：{频次价格}\n权益：{会员权益}\n适合：{适合人群}\n\n要求：\n1. 字数80-120字\n2. 突出生活品质\n3. 不强制推销\n4. 权益清晰\n5. 适合朋友圈推荐",fieldExplanations:{"订阅类型":"如「每周一束」「月度花盒」","频次价格":"多久一次、多少钱","会员权益":"额外享受什么","适合人群":"什么人适合"},outputFormat:"80-120字订阅推广文案",exampleOutput:"每周给自己买束花，是最简单的生活仪式感。「每周一花」订阅：每周三配送当季鲜花一束，99元/月（4次）。比单次购买省30%，花材每周不重样。会员还享受：节日花束9折、免费花艺课名额。适合想让家里一直有花的姐妹。随时可退订，没有绑定（仅供格式参考）",reviewChecklist:["价格是否准确","权益是否可兑现","退订说明是否清晰","无强制消费"],relatedTemplates:["flower-product-desc","flower-social-media"]});
T.push({id:"flower-short-video",title:"花店短视频脚本",slug:"flower-short-video",industry:"flower",task:"short-video",description:"为花店短视频撰写脚本",scenario:"拍摄花艺制作、养花教程时使用",notFor:"不适合用于广告片",materialsNeeded:["视频主题","展示内容","目标受众","时长"],prompt:"你是一位花艺短视频策划。请撰写脚本。\n\n主题：{视频主题}\n内容：{展示内容}\n受众：{目标受众}\n时长：{时长}\n\n要求：\n1. 视觉美感强\n2. 有实用价值\n3. 适合竖屏\n4. 分镜头描述",fieldExplanations:{"视频主题":"如「花束包装教程」「养花技巧」","展示内容":"具体展示什么","目标受众":"给谁看","时长":"视频时长"},outputFormat:"分镜头脚本",exampleOutput:"【开场3秒】画面：一堆散落的花材特写。字幕「3分钟教你包一束高级感花束」\n【中间25秒】画面：选花→修剪→螺旋手法→包装纸包裹→系丝带。每步配简短字幕说明\n【结尾5秒】画面：成品花束特写+送人场景。字幕「学会了吗？下次试试自己包」（仅供格式参考）",reviewChecklist:["步骤是否清晰","视觉是否美观","拍摄方案可执行","内容是否实用"],relatedTemplates:["flower-social-media","flower-product-desc"]});
T.push({id:"flower-brand-story",title:"花店品牌故事",slug:"flower-brand-story",industry:"flower",task:"brand-story",description:"为花店撰写品牌介绍",scenario:"更新社交媒体简介、制作名片时使用",notFor:"不适合用于商业计划书",materialsNeeded:["创业故事","花艺理念","选花标准","服务特色"],prompt:"你是一位品牌文案助手。请为花店撰写品牌故事。\n\n故事：{创业故事}\n理念：{花艺理念}\n选花：{选花标准}\n特色：{服务特色}\n\n要求：\n1. 字数150-250字\n2. 有美感有温度\n3. 真实不做作\n4. 适合小红书主页",fieldExplanations:{"创业故事":"为什么开花店","花艺理念":"怎么看待花艺","选花标准":"怎么选花材","服务特色":"和别家有什么不同"},outputFormat:"150-250字品牌故事",exampleOutput:"开花店是因为觉得「家里有花」这件事不应该很贵。以前买花总觉得花店的花太贵太正式，其实日常用花不需要那么隆重。所以我的店主打「日常花」：价格在50-150之间，不追求稀有花材，就用当季最新鲜的花做简单好看的搭配。每周三凌晨去花市选花，只拿当天到的新鲜货。包装也尽量简单，不过度包装。希望买花变成像买水果一样日常的事，每周给自己或家人带一束回去，让生活多一点颜色（仅供格式参考）",reviewChecklist:["故事是否真实","理念是否清晰","无虚构成分","语气是否自然"],relatedTemplates:["flower-social-media"]});

// MARKER_NEXT
writeFileSync(OUT, JSON.stringify(T, null, 2), 'utf-8');
console.log(`Part 7: Total ${T.length} templates`);
